GRANT SELECT ON GENERAL.AUDIT_TIMELINE_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_MONTH_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_STATUS_MONTH_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_STATUS_WEEK_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_WEEK_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.USER_PERMISSIONS_V TO "HSS_BACKEND";

GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_AGE_MONTH_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_AGE_WEEK_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_GENDER_MONTH_V TO "HSS_BACKEND";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_GENDER_WEEK_V TO "HSS_BACKEND";

GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_AGE_MONTH_V TO "DENTAL";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_AGE_WEEK_V TO "DENTAL";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_GENDER_MONTH_V TO "DENTAL";
GRANT SELECT ON GENERAL.SUBMISSIONS_DENTAL_GENDER_WEEK_V TO "DENTAL";

GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENT_TYPE TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENT_RULES TO "HSS_BACKEND" WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENTS TO "DENTAL" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENTS TO "MIDWIFERY" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENTS TO "CONSTELLATION_HEALTH" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.EVENTS TO "HIPMA" WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.CONFIG TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.ROLE_PERMISSIONS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.PERMISSION_DATA TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.USER_ROLES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.USER_DATA TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENERAL.ROLES_DATA TO "HSS_BACKEND" WITH GRANT OPTION;


GRANT SELECT ON DENTAL.DENTAL_SERVICE_SUBMISSIONS TO "GENERAL";
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_SUBMISSIONS TO "HSS_BACKEND";

GRANT SELECT ON DENTAL.DENTAL_SERVICE_SUBMISSIONS_DETAILS TO "GENERAL";
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_SUBMISSIONS_DETAILS TO "HSS_BACKEND";

GRANT SELECT ON DENTAL.STATUS_V TO "GENERAL";
GRANT SELECT, INSERT, UPDATE, DELETE ON  DENTAL.STATUS_V TO "HSS_BACKEND";

GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_FILES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_DEPENDENTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_STATUS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_GENDER TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_COMMENTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_REV TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_DUPLICATED_REQUESTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DENTAL.DENTAL_SERVICE_INTERNAL_FIELDS TO "HSS_BACKEND" WITH GRANT OPTION;


GRANT SELECT ON MIDWIFERY.STATUS_V TO "HSS_BACKEND";
GRANT SELECT ON MIDWIFERY.STATUS_V TO "GENERAL";
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_CLINIC_CONTACT_TYPES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_BIRTH_LOCATIONS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_COMMUNITY_LOCATIONS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_DUPLICATED_REQUESTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_GROUPS_COMMUNITIES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_LANGUAGES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_SERVICES_REV TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_SERVICES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_PREFERRED_CONTACT_TYPES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_OPTIONS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON MIDWIFERY.MIDWIFERY_STATUS TO "HSS_BACKEND" WITH GRANT OPTION;


GRANT SELECT ON HIPMA.STATUS_V TO "GENERAL";
GRANT SELECT ON HIPMA.STATUS_V TO "HSS_BACKEND";
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HEALTH_INFORMATION_REV TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_STATUS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_SITUATIONS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_REQUEST_TYPE TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_REQUEST_ACCESS_PERSONAL_HEALTH_INFORMATION TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_HSS_SYSTEMS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_HEALTH_SOCIAL_SERVICES_PROGRAM TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_FILES TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_DUPLICATED_REQUESTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HEALTH_INFORMATION TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_COPY_ACTIVITY_REQUEST TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON HIPMA.HIPMA_COPY_HEALTH_INFORMATION TO "HSS_BACKEND" WITH GRANT OPTION;


GRANT SELECT ON CONSTELLATION_HEALTH.STATUS_V TO "GENERAL";
GRANT SELECT ON CONSTELLATION_HEALTH.STATUS_V TO "HSS_BACKEND";
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DIAGNOSIS_HISTORY TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_DEMOGRAPHICS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_DUPLICATED_REQUESTS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_FAMILY_MEMBERS TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_LANGUAGE TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_REV TO "HSS_BACKEND" WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSTELLATION_HEALTH.CONSTELLATION_STATUS TO "HSS_BACKEND" WITH GRANT OPTION;




















