--------------------------------------BIZONT USER--------------------------------------
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(1, 'Mariazel', 'mariazel@bizont.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(2, 'Marcos', 'marcos@bizont.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 1, 7);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 1, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 1, 4);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 1, 6);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 2, 7);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 2, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 2, 4);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 2, 6);

--------------------------------------eServices USERS--------------------------------------
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(3, 'Dave.Rogers', 'Dave.Rogers@yukon.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(3, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(3, 4);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(3, 6);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(3, 7);


INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(4, 'Adam LaBar', 'Adam.Labar@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(5, 'Alethea Stobbe', 'Alethea.Stobbe@yukon.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 4, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 4, 6);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 5, 2); 
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 4, 4);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 5, 6);


--------------------------------------HIPMA USERS--------------------------------------
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(6, 'Lonnie Ariss', 'Lonnie.Ariss@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(7, 'Emily MacLeod', 'Emily.MacLeod@yukon.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 6, 4);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 7, 4);

--------------------------------------MIDWIFERY USERS--------------------------------------

INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(62, 'Kayla Gagnon', 'Kayla.Gagnon@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(63, 'Christina Kaiser', 'Christina.Kaiser@yukon.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 62, 6);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 63, 6);



--------------------------------------DENTAL USERS--------------------------------------
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(101, 'Gemma.Richardson', 'Gemma.Richardson@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(121, 'Leonardo.Lin', 'Leonardo.Lin@yukon.ca');
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 101, 7);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES( 121, 7);





--------------------------------------CONSTELLATION USERS--------------------------------------
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(61, 'Aude St.Louis', 'Aude.St.Louis@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(64, 'Randeelyn Koshman', 'Randeelyn.Koshman@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(65, 'Neysa Laszkiewicz', 'Neysa.Laszkiewicz@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(66, 'Laura Gray Ellis', 'Laura.Gray-Ellis@yukon.ca');
INSERT INTO "GENERAL".USER_DATA (ID, USER_NAME, USER_EMAIL) VALUES(41, 'Melissa Laluk', 'Melissa.Laluk@yukon.ca');


INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(42, 41, 2);

INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(61, 61, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(64, 64, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(65, 65, 2);
INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(66, 66, 2);










INSERT INTO "GENERAL".USER_ROLES (USER_ID, ROLE_ID) VALUES(22, 21, 4);
