
CREATE TABLE GENERAL.COMMUNITY_LOCATIONS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DESCRIPTION NVARCHAR2(500),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT SELECT ON "GENERAL"."COMMUNITY_LOCATIONS" TO "CONSTELLATION_HEALTH";

INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Beaver Creek');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Burwash Landing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Carcross');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Carmacks');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Dawson City');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Destruction Bay');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Faro');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Haines Junction');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Ibex Valley');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Marsh Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Mayo');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Mount Lorne');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Old Crow');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Pelly Crossing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Ross River');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Tagish');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Teslin');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Watson Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Whitehorse');

ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH ADD COMMUNITY_LOCATED NVARCHAR2(500);
ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_REV ADD COMMUNITY_LOCATED NVARCHAR2(500);

INSERT INTO MIDWIFERY.MIDWIFERY_BIRTH_LOCATIONS VALUES (4, 'hospital_2', 'I''d prefer to give birth at a hospital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO MIDWIFERY.MIDWIFERY_BIRTH_LOCATIONS VALUES (5, 'out_hospital', 'I''m considering an out of hospital birth.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO MIDWIFERY.MIDWIFERY_GROUPS_COMMUNITIES VALUES (11, 'mental_wellness_2', 'Person with mental wellness concerns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO MIDWIFERY.MIDWIFERY_GROUPS_COMMUNITIES VALUES (12, 'substance_concerns', 'Person with substance use concerns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
