
CREATE TABLE GENERAL.COMMUNITY_LOCATIONS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DESCRIPTION NVARCHAR2(500),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT SELECT ON "GENERAL"."COMMUNITY_LOCATIONS" TO "CONSTELLATION_HEALTH";

INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Beaver Creek');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Burwash Landing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Carcross');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Carmacks');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Dawson City');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Destruction Bay');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Faro');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Haines Junction');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES('Ibex Valley');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Marsh Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Mayo');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Mount Lorne');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Old Crow');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Pelly Crossing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Ross River');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Tagish');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Teslin');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Watson Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS
(DESCRIPTION)
VALUES( 'Whitehorse');

ALTER TABLE GENERAL.GENERAL ADD COMMUNITY_LOCATED VARCHAR2(255);
