

CREATE TABLE CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DESCRIPTION NVARCHAR2(500),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(1, 'Beaver Creek');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(2, 'Burwash Landing');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(3, 'Carcross');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(4, 'Carmacks');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(5, 'Dawson City');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(6, 'Destruction Bay');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(7, 'Faro');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(8, 'Haines Junction');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(9, 'Ibex Valley');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(10, 'Marsh Lake');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(11, 'Mayo');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(12, 'Mount Lorne');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(13, 'Old Crow');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(14, 'Pelly Crossing');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(15, 'Ross River');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(16, 'Tagish');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(17, 'Teslin');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(18, 'Watson Lake');
INSERT INTO CONSTELLATION_HEALTH.COMMUNITY_LOCATIONS
(ID, DESCRIPTION)
VALUES(19, 'Whitehorse');

ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH ADD COMMUNITY_LOCATED VARCHAR2(255);
