import express, { Request, Response, Router } from "express";
import cors from "cors";
import helmet from "helmet";
import path from 'path';
import { userRouter, constellationRouter, midwiferyRouter, hipmaRouter, generalRouter, dentalRouter } from "./routes";
import * as config from './config';
import { doHealthCheck } from "./utils/healthCheck";
import { configureAuthentication } from "./routes/auth"

const app = express();
const sufixPath = '/index.html';
const routes: Record<string, Router> = {
  "/api/user": userRouter,
  "/api/constellation": constellationRouter,
  "/api/midwifery": midwiferyRouter,
  "/api/hipma": hipmaRouter,
  "/api/general": generalRouter,
  "/api/dental": dentalRouter
};

const maxRequestBodySize = '10mb';
app.use(express.json({limit: maxRequestBodySize})) // for parsing application/json
app.use(express.urlencoded({ extended: true, limit: maxRequestBodySize})) // for parsing application/x-www-form-urlencoded
//app.use(helmet());
app.use(
    helmet.contentSecurityPolicy({
      directives: {
        'default-src': [ "'self'" ],
        'base-uri': [ "'self'" ],
        'block-all-mixed-content': [],
        'font-src': [ "'self'", 'https:', 'data:' ],
        'frame-ancestors': [ "'self'" ],
        'img-src': [ "'self'", 'data:' ],
        'object-src': [ "'none'" ],
        'script-src': [ "'self'" ],
        'script-src-attr': [ "'none'" ],
        'style-src': [ "'self'", 'https:', "'unsafe-inline'" ]
      },
    })
  );

// very basic CORS setup
app.use(cors({
  origin: config.FRONTEND_URL,
  optionsSuccessStatus: 200,
  credentials: true
}));

configureAuthentication(app);

app.get("/api/healthCheck", (req: Request, res: Response) => {
  doHealthCheck(res);
});

// Adding routes.
for (const url in routes) {
  app.use(url, routes[url]);
}

// set up rate limiter: maximum of five requests per minute
var RateLimit = require('express-rate-limit');
var limiter = RateLimit({
  windowMs: 1*60*1000, // 1 minute
  max: 5000
});


// apply rate limiter to all requests
app.use(limiter);

/*if (config.NODE_ENV !== "production")
  baseWebPath = "/dist/web";
*/
// serves the static files generated by the front-end
app.use(express.static(path.join(__dirname, "web")));

// if no other routes match, just send the front-end
app.use((req: Request, res: Response) => {
  res.sendFile(path.join(__dirname, "web") + sufixPath)
})

app.listen(config.API_PORT, () => {
  console.log(`API listenting on port ${config.API_PORT}`);
});
